version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-korean
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./db_persistent_storage:/var/lib/postgresql/data
