version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-korean
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5532:5432"
    volumes:
      - ./db_persistent_storage:/var/lib/postgresql/data
