name: Build rust app and run tests

on:
  push:
    branches: [ "master" ]
    paths: [ "backend/**" ]
  pull_request:
    branches: [ "master" ]
    paths: [ "backend/**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3
        
      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
