name: Rust and SQLx Migrate

on:
  push:
    branches: [ "master" ]
    paths: [ "backend/**" ]
  pull_request:
    branches: [ "master" ]
    paths: [ "backend/**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change directory
        run: cd backend
        
      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
